apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-update-deployment
  labels:
    app: cluster-update
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-update
  template:
    metadata:
      labels:
        app: cluster-update
    spec:
      containers:
      - name: cluster-update-container
        image: cluster-update
        ports:
        - containerPort: 25565
        volumeMounts:
        - name: registry-secret
          mountPath: "/mnt/registry"
          readOnly: true
        - name: web-server-secret
          mountPath: "/mnt/images/web-server"
          readOnly: true
        - name: cluster-update-secret
          mountPath: "/mnt/images/cluster-update"
          readOnly: true
      volumes:
      - name: registry-secret
        secret:
          secretName: registry-secret
      - name: web-server-secret
        secret:
          secretName: web-server-secret
      - name: cluster-update-secret
        secret:
          secretName: cluster-update-secret
