apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-update-deployment
  labels:
    app: cluster-update
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-update
  template:
    metadata:
      labels:
        app: cluster-update
    spec:
      containers:
      - name: cluster-update-container
        image: cluster-update
        ports:
        - containerPort: 25565
        volumeMounts:
        - name: registry-url
          mountPath: "/mnt/registry-url"
          readOnly: true
      volumes:
      - name: registry-url
        secret:
          secretName: secret-registry
