apiVersion: v1
kind: Service
metadata:
  name: cluster-update-service
  labels:
    app: cluster-update
spec:
  type: NodePort
  ports:
  - port: 25565
    targetPort : 25565
    protocol: TCP
    name: http
  selector:
    app: cluster-update
