apiVersion: v1
kind: Pod
metadata:
  name: pod-update-deployment
spec:
  containers:
  - name: container-update-deployment
    image: ubuntu:16.04
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    volumeMounts:
    - name: registry-url
      mountPath: "/mnt/registry-url"
      readOnly: true
  volumes:
  - name: registry-url
    secret:
      secretName: secret-registry
