apiVersion: v1
kind: Service
metadata:
  name: web-server-service
  labels:
    app: web-server
spec:
  type: NodePort
  ports:
  - port: 8888
    protocol: TCP
    name: http
  selector:
    app: web-server
