apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  labels:
    app: webserver
spec:
  type: NodePort
  ports:
  - port: 8888
    protocol: TCP
    name: http
  selector:
    app: webserver
